import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import TimeTableInput from "../components/TimeTableInput";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TimeTabler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header/>
        <TimeTableInput/>
      </main>
    </div>
  );
}
