import Head from "next/head";
import Image from "next/image";
import MainPage from "../components/MainPage";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Timetabler</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
				<link
					href="https://fonts.googleapis.com/css2?family=Comfortaa&display=swap"
					rel="stylesheet"
				></link>
			</Head>

			{/* <main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
			</main> */}
			<MainPage />

			<footer>
				<div className="container">
					<hr></hr>
					<p>
						Made by{" "}
						<a href="https:www.edwinroosevelt.com" target="_blank">
							Edwin Roosevelt
						</a>
					</p>
				</div>
			</footer>
		</div>
	);
}
